### ISSUE TITLE
Problems with running Shenango's synthetic application

### ISSUE THREAD

**Issue by piginthesettingsun** [shenango/shenango#2]
Could I run two spin-servers on Shenango simultaneously in a simple way, and schedule them with Shenango according to workload varying with time? 
And could you clarify the protocol used by Shenango's synthetic application so that I can test Shenango’s synthetic application with our own workload generator?
Many thanks!

**Comment by aousterh** [comment]
Yes, you can run multiple Shenango spin-servers on the same machine. If you configure one or more client instances to generate load for each spin-server and set the barrier-leader to be the same for all of them, then the clients will coordinate their load generation, so that your spin-servers all receive load at the same time. There's an example for Caladan [here](https://github.com/shenango/caladan-all/blob/main/paper_experiments.py#L12); the same approach will work for Shenango.

Regarding workloads that vary with time, Shenango's load generator by default runs short samples at several increasing loads, with gaps between samples. If you want more complicated load patterns, you can use the loadshift parameter, as demonstrated [here](https://github.com/shenango/all/blob/master/experiment.py#L326).

The format of the payloads for Shenango's synthetic application can be found [here](https://github.com/shenango/shenango/blob/master/apps/synthetic/src/payload.rs).

**Comment by piginthesettingsun** [comment]
I notice that there is netbench.cc under /apps/bench. Could I simply modify it to run as a synthetic server, and schedule it as an LC application in Shenango?

**Comment by aousterh** [comment]
Yes, you should be able to modify netbench to work with the synthetic load generator. I suggest starting with netbench2 - you should only need to remove the [cpu field from the payload](https://github.com/shenango/shenango/blob/5748d92b2a67b196c40f81683a8056b3ac629cc8/apps/bench/netbench2.cc#L124).

**Comment by piginthesettingsun** [comment]
How many long-term TCP flows can I keep concurrently (how many threads can be scheduled simultaneously)? And could I modify the concurrency limitations?

**Comment by aousterh** [comment]
I'm not sure exactly what the limitations are here. We've run experiments with up to 1200 concurrent TCP connections in one runtime but I expect you could run with substantially higher numbers of connections. Feel free to try higher values and follow up with any limitations you encounter.
